Fix for review

diff --git a/container/bisect/build b/container/bisect/build
--- a/container/bisect/build
+++ b/container/bisect/build
@@ -8,8 +8,14 @@ docker_skip_rebuild "bisect"
 
 load_cci_defaults
 
+download_repo "compass-ci" "$git_branch_cbs"
+download_repo "lkp-tests" "$git_branch_lkp"
+if [ $? -ne 0 ]; then
+        echo "Failed to clone lkp-tests, copying SRC directory instead..."
+        cp -r "$LKP_SRC" lkp-tests
+fi
+
 docker build -t bisect .
 
 push_image bisect:latest
 
-#rm bisect
