fix(qcow2rootfs): process should exit if generate initramfs.img failed
Signed-off-by: Yu Chuan <13186087857@163.com>

diff --git a/container/qcow2rootfs/bin/common b/container/qcow2rootfs/bin/common
--- a/container/qcow2rootfs/bin/common
+++ b/container/qcow2rootfs/bin/common
@@ -151,6 +151,11 @@ create_get_initrd() {
 	local initrd_lkp
 	initrd_lkp=$(find ./boot -name "initramfs.lkp*") && export ROOTFS_INITRD_LKP=$initrd_lkp
 
+	[ -f "$ROOTFS_INITRD_LKP" ] || {
+		echo "Failed to generate \"$ROOTFS_INITRD_LKP\""
+		exit 8
+	}
+
 	echo
 	echo "initrd_lkp: $ROOTFS_INITRD_LKP"
 }
